name: "🐞 Bug Report"
description: "Report a bug or unexpected behavior"
labels: ["type: bug"]
body:
  - type: markdown
    attributes:
      value: |
        > **Internal use.** Do not include secrets, credentials, or PII in issue text or attachments.

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "What went wrong?"
      placeholder: "Clear and concise description of the bug."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "How do we trigger this bug?"
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      placeholder: "What should have happened?"

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      options:
        - "P0 – Critical"
        - "P1 – High"
        - "P2 – Medium"
        - "P3 – Low"
      default: 2
    validations:
      required: true

  - type: checkboxes
    id: pii_check
    attributes:
      label: Data Safety Verification
      description: Confirm that no PII, PHI, credentials, or other sensitive data is included in this issue.
      options:
        - label: I confirm this issue does not contain sensitive data.
          required: true
